import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, Check, ChevronRight, CircleDot, Code2, Download, ExternalLink, Menu, MessageCircle, Network, Play, RotateCcw, Send, Sparkles, X } from 'lucide-react';
import { projects, skillGroups } from './data/projects';
import logo from '../zaaraquadri.jpeg';
import './styles.css';

const navItems = ['About', 'Experience', 'Projects', 'Skills', 'Learning', 'Education', 'Contact'];

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [selectedProject, setSelectedProject] = useState(null);
  const [caseStudy, setCaseStudy] = useState(null);

  useEffect(() => {
    document.body.style.overflow = selectedProject || caseStudy ? 'hidden' : '';
    return () => { document.body.style.overflow = ''; };
  }, [selectedProject, caseStudy]);

  const jumpTo = (id) => { document.getElementById(id.toLowerCase())?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false); };

  return (
    <div className="site-shell">
      <div className="grain" />
      <header className="nav-wrap">
        <nav className="nav container" aria-label="Main navigation">
          <button className="brand" onClick={() => jumpTo('top')}><span className="brand-mark"><img src={logo} alt="Zaara Quadri" /></span><span>Zaara<span className="brand-dot">.</span></span></button>
          <button className="menu-toggle" aria-label="Toggle menu" onClick={() => setMenuOpen(!menuOpen)}><Menu size={20} /></button>
          <div className={`nav-links ${menuOpen ? 'open' : ''}`}>
            {navItems.map((item) => <button key={item} onClick={() => jumpTo(item)}>{item}</button>)}
            <a className="nav-resume" href="mailto:zquadri04@gmail.com?subject=Resume%20request">Resume <ArrowUpRight size={15} /></a>
          </div>
        </nav>
      </header>

      <main id="top">
        <section className="hero container">
          <div className="hero-copy reveal">
            <div className="eyebrow"><span className="eyebrow-line" /> Available for software engineering opportunities</div>
            <p className="hero-kicker">Software Engineer <span>/</span> Full-Stack Developer <span>/</span> AI-Enabled Solutions</p>
            <h1>Building practical software<span className="accent">,</span><br />intelligent systems<span className="accent">,</span><br />and polished experiences<span className="accent">.</span></h1>
            <p className="hero-text">I'm Zaara Quadri, a Software Engineer from Hyderabad focused on full-stack development, enterprise applications, AI/ML solutions, and user-focused products.</p>
            <div className="hero-actions"><button className="button button-primary" onClick={() => jumpTo('projects')}>View my work <ArrowUpRight size={17} /></button><a className="button button-ghost" href="mailto:zquadri04@gmail.com?subject=Resume%20request">Download resume <Download size={16} /></a><button className="text-link" onClick={() => jumpTo('contact')}>Let's connect <ChevronRight size={16} /></button></div>
            <div className="social-row"><a href="https://github.com/zaaraquadrii" target="_blank" rel="noreferrer"><Code2 size={17} /> github.com/zaaraquadrii</a><a href="https://www.linkedin.com" target="_blank" rel="noreferrer"><Network size={17} /> LinkedIn</a></div>
          </div>
          <div className="hero-visual reveal reveal-delay">
            <div className="orbit orbit-one" /><div className="orbit orbit-two" />
            <div className="terminal-card"><div className="terminal-top"><span><i /><i /><i /></span><span>zaara@portfolio ~</span><span>•••</span></div><div className="terminal-body"><p><span className="terminal-muted">$</span> whoami</p><p className="terminal-gap">Sayeda Zaara Quadri<br /><span className="terminal-accent">Software Engineer</span></p><p><span className="terminal-muted">$</span> stack --current</p><div className="terminal-list">{['React.js', '.NET / REST APIs', 'SQL + PostgreSQL', 'Python / AI / ML', 'Salesforce'].map((item, index) => <span key={item}><b>0{index + 1}</b>{item}</span>)}</div><p className="terminal-cursor"><span className="terminal-muted">$</span> <span className="blink">_</span></p></div></div>
            <div className="visual-caption"><span className="status-dot" /> Building with intent <span>↗</span></div>
          </div>
        </section>

        <div className="marquee-band"><div className="marquee-inner">REACT <span>✦</span> .NET <span>✦</span> PYTHON <span>✦</span> REST APIS <span>✦</span> AI / ML <span>✦</span> SALESFORCE <span>✦</span> REACT <span>✦</span> .NET <span>✦</span> PYTHON <span>✦</span></div></div>

        <section className="section container about-section" id="about"><div className="section-intro"><span className="section-number">01</span><span className="section-rule" /><span>About</span></div><div className="about-grid"><div><h2>Curious by nature.<br /><em>Practical</em> by default.</h2></div><div className="about-copy"><p>I've completed my engineering in Computer Science and build software where thoughtful interfaces meet dependable systems.</p><p>My work spans enterprise applications, APIs, dashboards, attendance systems, database-driven workflows, automation, AI/ML experiments, and client websites. I care about the detail that makes software feel clear, useful, and ready for the real world.</p><div className="about-note"><span>Based in</span><strong>Hyderabad, India</strong><span>Working across</span><strong>Product · Platform · Data</strong></div></div></div></section>

        <section className="section experience-section" id="experience"><div className="container"><div className="section-intro"><span className="section-number">02</span><span className="section-rule" /><span>Experience</span></div><div className="experience-card"><div className="experience-meta"><span>Nov 2025 — 2026</span><span>Hyderabad, India</span></div><div className="experience-main"><div><p className="mini-label">SFON Technologies</p><h2>Full Stack Developer<br /><em>Software engineering experience</em></h2></div><div className="experience-body"><p>Building and maintaining enterprise applications across frontend, backend, data, and business-rule layers.</p><div className="tag-list">{['React.js', 'C# / .NET', 'REST APIs', 'SQL Server', 'Dashboards', 'Git / GitHub'].map(tag => <span key={tag}>{tag}</span>)}</div></div></div><div className="experience-foot"><span>Hands-on across</span><strong>Employee management · Leave · Shifts · Attendance · Reporting</strong><ArrowUpRight size={18} /></div></div></div></section>

        <section className="section projects-section container" id="projects"><div className="section-intro"><span className="section-number">03</span><span className="section-rule" /><span>Selected work</span></div><div className="projects-heading"><div><h2>Work that moves<br /><em>from idea to useful.</em></h2></div><p>Real client work, enterprise systems, and focused prototypes. Explore the interactive previews to see the thinking behind each build.</p></div><div className="project-grid">{projects.map((project) => <ProjectCard key={project.id} project={project} onPreview={setSelectedProject} onCaseStudy={setCaseStudy} />)}</div></section>

        <section className="section skills-section" id="skills"><div className="container"><div className="section-intro"><span className="section-number">04</span><span className="section-rule" /><span>Capabilities</span></div><div className="skills-heading"><h2>A toolkit for<br /><em>useful complexity.</em></h2><p>No arbitrary percentages. Just the technologies and concepts I use to make things work.</p></div><div className="skills-grid">{skillGroups.map(([group, skills]) => <div className="skill-group" key={group}><div className="skill-group-title"><span>{group}</span><span>↗</span></div><div className="skill-pills">{skills.map(skill => <span key={skill}>{skill}</span>)}</div></div>)}</div></div></section>

        <section className="section learning-section container" id="learning"><div className="learning-card"><div><div className="section-intro"><span className="section-number">05</span><span className="section-rule" /><span>Learning in motion</span></div><h2>Salesforce Trailhead<br /><em>learning & projects.</em></h2></div><div className="learning-content"><p>Exploring how data, security, service workflows, and automation come together in customer support environments.</p><div className="learning-list">{['Data Management', 'Data Security', 'Reports & Dashboards', 'Flow Builder Basics', 'Service Cloud Essentials', 'Agentforce Service Configuration', 'User Engagement'].map(item => <span key={item}><Check size={14} />{item}</span>)}</div><span className="concept-label">Learning implementation · Not presented as a certification</span></div></div></section>

        <section className="section education-section container" id="education"><div className="section-intro"><span className="section-number">06</span><span className="section-rule" /><span>Education</span></div><div className="education-row"><div><h2>Deccan College of Engineering<br /><em>and Technology</em></h2><p>B.E. / Engineering — Computer Science<br />Hyderabad, Telangana, India</p></div><div className="cgpa"><span>CGPA</span><strong>8.57</strong><small>/ 10</small></div></div></section>

        <section className="resume-banner container"><div><span className="mini-label">A closer look</span><h2>Interested in my<br /><em>experience?</em></h2></div><div><p>View my resume or reach out to start a conversation about software, systems, and what we could build next.</p><a className="button button-light" href="mailto:zquadri04@gmail.com?subject=Resume%20request">Request resume <ArrowUpRight size={17} /></a></div></section>

        <section className="section contact-section container" id="contact"><div className="section-intro"><span className="section-number">07</span><span className="section-rule" /><span>Contact</span></div><div className="contact-grid"><div><h2>Let's build<br /><em>something useful.</em></h2><p>I'm open to software engineering, full-stack development, AI-enabled applications, and technical product opportunities.</p><div className="contact-links"><a href="mailto:zquadri04@gmail.com"><span>Email</span>zquadri04@gmail.com <ArrowUpRight size={16} /></a><a href="https://github.com/zaaraquadrii" target="_blank" rel="noreferrer"><span>GitHub</span>zaaraquadrii <ArrowUpRight size={16} /></a><a href="https://www.linkedin.com" target="_blank" rel="noreferrer"><span>LinkedIn</span>Zaara Quadri <ArrowUpRight size={16} /></a></div></div><ContactForm /></div></section>
      </main>
      <footer className="footer container"><span>© 2026 Sayeda Zaara Quadri</span><span>Built with curiosity & care</span><button onClick={() => jumpTo('top')}>Back to top ↑</button></footer>
      {selectedProject && <ProjectPreview project={selectedProject} onClose={() => setSelectedProject(null)} />}
      {caseStudy && <CaseStudy project={caseStudy} onClose={() => setCaseStudy(null)} onPreview={() => { setCaseStudy(null); setSelectedProject(caseStudy); }} />}
    </div>
  );
}

function ProjectCard({ project }) {
  return <article className={`project-card project-${project.id}`}><div className="project-card-top"><span className="project-number">{project.number}</span><span className="project-category">{project.category}</span></div><div className="project-card-content"><div className="project-copy"><h3>{project.title}</h3><p className="project-subtitle">{project.subtitle}</p><p className="project-description">{project.description}</p><div className="project-tags">{project.technologies.map(tag => <span key={tag}>{tag}</span>)}</div></div><div className="project-preview-panel">{project.liveDemo ? <><div className="preview-frame-wrap"><iframe src={project.liveDemo} title={`${project.title} live preview`} loading="lazy" sandbox="allow-scripts allow-same-origin allow-forms" /></div><div className="project-preview-actions"><a href={project.liveDemo} target="_blank" rel="noreferrer">Open live site <ExternalLink size={14} /></a></div></> : <div className="preview-placeholder"><span>Live preview unavailable</span></div>}</div></div></article>;
}

function ContactForm() { const [sent, setSent] = useState(false); const [form, setForm] = useState({ name: '', email: '', message: '' }); const submit = (event) => { event.preventDefault(); window.location.href = `mailto:zquadri04@gmail.com?subject=Portfolio%20message%20from%20${encodeURIComponent(form.name)}&body=${encodeURIComponent(form.message)}%0A%0AReply%20to:%20${form.email}`; setSent(true); }; return <form className="contact-form" onSubmit={submit}><label>Name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Your name" /></label><label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></label><label>Message<textarea required value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} placeholder="Tell me a little about what you're building..." /></label><button className="button button-primary" type="submit">{sent ? 'Email draft opened' : 'Send message'} <Send size={15} /></button><small>Your email client will open with the message pre-filled.</small></form>; }

function CaseStudy({ project, onClose, onPreview }) {
  const canPreview = Boolean(project.hasInteractivePreview);

  return <div className="overlay"><div className="case-study modal-panel"><button className="modal-close" onClick={onClose} aria-label="Close"><X /></button><div className="case-hero"><span className="mini-label">{project.category}</span><h2>{project.title}<br /><em>{project.subtitle}</em></h2>{project.liveDemo ? <a className="button button-primary" href={project.liveDemo} target="_blank" rel="noreferrer">Open live site <ExternalLink size={15} /></a> : canPreview && <button className="button button-primary" onClick={onPreview}>Open interactive preview <Play size={15} fill="currentColor" /></button>}</div><div className="case-grid">{[['Problem', project.caseStudy.problem], ['Solution', project.caseStudy.solution], ['My role', project.caseStudy.role], ['Challenges', project.caseStudy.challenges], ['Outcome', project.caseStudy.outcome]].map(([title, text]) => <div key={title}><span className="mini-label">{title}</span><p>{text}</p></div>)}<div className="architecture"><span className="mini-label">Architecture</span><div><b>Frontend</b><ChevronRight /><b>REST API</b><ChevronRight /><b>Backend</b><ChevronRight /><b>Database</b></div></div></div></div></div>;
}

function ProjectPreview({ project, onClose }) { const [view, setView] = useState('dashboard'); const [done, setDone] = useState(false); const [mood, setMood] = useState('Chill'); const [filter, setFilter] = useState('All'); useEffect(() => { setView('dashboard'); setDone(false); }, [project]); const reset = () => { setView('dashboard'); setDone(false); setMood('Chill'); setFilter('All'); }; return <div className="overlay preview-overlay"><div className="preview-modal"><div className="preview-header"><div><span className="preview-label"><CircleDot size={13} /> Interactive Preview</span><h2>{project.title}</h2></div><div className="preview-actions"><button onClick={reset} title="Reset demo"><RotateCcw size={16} /></button><button onClick={onClose} title="Close preview"><X size={19} /></button></div></div><div className="preview-body">{project.previewType === 'clinic' && <ClinicPreview view={view} setView={setView} />}{project.previewType === 'ems' && <EmsPreview view={view} setView={setView} filter={filter} setFilter={setFilter} />}{project.previewType === 'verdura' && <VerduraPreview done={done} setDone={setDone} />}{project.previewType === 'music' && <MusicPreview mood={mood} setMood={setMood} />}{project.previewType === 'attendance' && <AttendancePreview done={done} setDone={setDone} />}{project.previewType === 'salesforce' && <SalesforcePreview view={view} setView={setView} filter={filter} setFilter={setFilter} />}</div></div></div>; }

const DemoNav = ({ items, active, setActive }) => <aside className="demo-nav"><div className="demo-brand">{items[0] === 'Home' ? 'VEEDENTES' : items[0] === 'Dashboard' ? 'SFON <span>EMS</span>' : 'SUPPORT DESK'}</div>{items.map(item => <button className={active === item ? 'active' : ''} key={item} onClick={() => setActive(item)}>{item}<ChevronRight size={14} /></button>)}</aside>;
function ClinicPreview({ view, setView }) { const [booked, setBooked] = useState(false); return <div className="demo-app clinic-demo"><DemoNav items={['Home', 'Services', 'About', 'Contact', 'Admin'] } active={view} setActive={setView} /><div className="clinic-main">{view === 'Admin' ? <><div className="demo-topline"><div><span className="mini-label">Operations</span><h3>Appointment desk</h3></div><button className="small-button" onClick={() => setBooked(false)}>Export .xlsx <Download size={13} /></button></div><div className="metric-row"><div><span>Today's requests</span><strong>{booked ? '07' : '06'}</strong></div><div><span>Confirmed</span><strong>04</strong></div><div><span>Pending</span><strong>{booked ? '03' : '02'}</strong></div></div><div className="demo-table"><div className="table-head"><span>Patient</span><span>Service</span><span>Status</span></div>{['Aarav Mehta', 'Nisha Reddy', booked ? 'Zaara Quadri' : 'Demo Patient'].map((name, i) => <div className="table-row" key={name}><span>{name}</span><span>{i === 0 ? 'Consultation' : 'General checkup'}</span><b className={i === 2 && booked ? 'pending' : ''}>{i === 2 && booked ? 'New' : 'Confirmed'}</b></div>)}</div></> : <><div className="clinic-hero"><span className="mini-label">Veedentes dental studio</span><h3>Care that makes<br /><em>you smile.</em></h3><p>Modern dental care in a calm, welcoming space.</p><button className="button button-light" onClick={() => setView('Book appointment')}>Book an appointment <ArrowUpRight size={15} /></button></div><div className="clinic-bottom"><div><span className="mini-label">01 / Services</span><strong>Thoughtful care,<br />every visit.</strong></div><div><span className="mini-label">02 / Patient-first</span><strong>Simple booking<br />without the wait.</strong></div></div></>}</div>{view === 'Book appointment' && <div className="demo-toast"><div><span className="mini-label">Appointment request</span><h4>Pick a convenient time</h4><input placeholder="Your name" /><input placeholder="Preferred service" /><button className="small-button" onClick={() => { setBooked(true); setView('Admin'); }}>Send to WhatsApp <MessageCircle size={13} /></button></div><button onClick={() => setView('Home')}><X size={16} /></button></div>}</div>; }
function EmsPreview({ view, setView, filter, setFilter }) { const stats = [['Present', '184', 'positive'], ['Absent', '12', ''], ['Late', '08', 'warn'], ['Early out', '05', ''], ['On leave', '16', '']]; return <div className="demo-app ems-demo"><DemoNav items={['Dashboard', 'Employees', 'Attendance', 'Leave', 'Shifts', 'Reports']} active={view} setActive={setView} /><div className="app-main"><div className="demo-topline"><div><span className="mini-label">Tuesday, 23 September 2026</span><h3>{view}</h3></div><div className="filter-row"><select value={filter} onChange={e => setFilter(e.target.value)}><option>All departments</option><option>Engineering</option><option>Operations</option></select><button className="avatar-button">ZQ</button></div></div><div className="ems-stats">{stats.map(([label, value, style]) => <div key={label}><span>{label}</span><strong className={style}>{value}</strong><small>vs last month ↗</small></div>)}</div><div className="chart-panel"><div className="chart-title"><span>Attendance overview</span><span className="chart-legend"><i /> Present <i /> Absent</span></div><div className="fake-chart"><div className="chart-bars">{[52, 70, 60, 88, 75, 94, 82, 68, 87, 76, 98, 84].map((h, i) => <span style={{ height: `${h}%` }} key={i}><i /></span>)}</div><div className="chart-labels">{['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'].map(m => <small key={m}>{m}</small>)}</div></div></div><div className="activity-panel"><span className="mini-label">Recent activity</span><div><b>Biometric sync complete</b><span>Today, 09:14</span></div><div><b>Leave request approved</b><span>Today, 08:42</span></div></div></div></div>; }
function VerduraPreview({ done, setDone }) { return <div className="ai-demo"><div className="ai-brand"><span className="plant-icon">✦</span><span>verdura <b>scan</b></span><span className="demo-badge">Demo Preview</span></div><div className="ai-content"><div className="upload-zone"><div className="leaf-shape">✿</div><h3>Upload a plant image</h3><p>We'll demonstrate the prediction flow with sample inference.</p><button className="small-button" onClick={() => setDone(true)}>Choose demo image</button></div><div className={`prediction-card ${done ? 'show' : ''}`}>{done ? <><span className="mini-label">Prediction result</span><div className="prediction-title"><span className="result-plant">🍃</span><div><h3>Tomato — Late Blight</h3><p>Demo inference shown for portfolio demonstration</p></div></div><div className="confidence"><span>Confidence</span><strong>94.7%</strong><div><i /></div></div><div className="recommendation"><Sparkles size={15} /><span>Recommended action<br /><b>Consult appropriate plant disease management guidance.</b></span></div></> : <><span className="mini-label">Ready when you are</span><h3>Model output<br /><em>appears here.</em></h3><p>Upload a sample to see the result state.</p></>}</div></div></div>; }
function MusicPreview({ mood, setMood }) { const songs = { Chill: ['Sunset Lover', 'Bloom', 'Night Drive'], Happy: ['Good Days', 'Golden Hour', 'Electric Feel'], Energetic: ['On Top', 'Runaway', 'Higher'], Sad: ['The Night We Met', 'Sparks', 'Youth'] }; return <div className="music-demo"><div className="music-header"><div><span className="mini-label">Mood / Mix</span><h3>Find your frequency.</h3></div><span className="music-chip">700 song dataset</span></div><p className="music-question">How are you feeling today?</p><div className="mood-row">{['Happy', 'Chill', 'Energetic', 'Sad', 'Relaxed'].map(item => <button className={mood === item ? 'selected' : ''} onClick={() => setMood(item)} key={item}>{item === 'Happy' ? '😊' : item === 'Chill' ? '😌' : item === 'Energetic' ? '🔥' : item === 'Sad' ? '💙' : '🌙'}<span>{item}</span></button>)}</div><div className="music-results"><div className="queue"><span className="mini-label">For your {mood.toLowerCase()} mood</span>{(songs[mood] || songs.Chill).map((song, i) => <div className="song-row" key={song}><span className="song-index">0{i + 1}</span><span><b>{song}</b><small>{['Petit Biscuit', 'The Paper Kites', 'M83'][i]}</small></span><span className="mood-match">{91 - i * 4}% match</span><button><Play size={12} fill="currentColor" /></button></div>)}</div><div className="player"><div className="album-art">{mood === 'Energetic' ? '↗' : '◒'}</div><span className="mini-label">Now playing</span><h4>{(songs[mood] || songs.Chill)[0]}</h4><p>Petit Biscuit · {mood}</p><div className="player-line"><i /></div><div className="player-controls"><span>↶</span><button><Play size={15} fill="currentColor" /></button><span>↷</span></div></div></div></div>; }
function AttendancePreview({ done, setDone }) { return <div className="phone-stage"><div className="phone-frame"><div className="phone-notch" /><div className="phone-screen"><div className="phone-top"><span>9:41</span><span>•••</span></div><div className="attendance-brand"><span>FIELD CHECK-IN</span><b>Good Morning, Zaara</b></div><div className="selfie-preview"><div className="selfie-face">◡</div><span>{done ? 'Verified selfie' : 'Selfie verification'}</span></div><div className="location-box"><div><CircleDot size={16} /><span>Location<br /><b>Detected</b></span></div><span>17.3850<br />78.4867</span></div><button className={`attendance-button ${done ? 'done' : ''}`} onClick={() => setDone(!done)}>{done ? <><Check size={16} /> Attendance marked</> : 'Mark attendance'}</button><small>/mark-attendance</small></div></div><div className="phone-copy"><span className="mini-label">Mobile / full-stack</span><h3>Verification<br /><em>without friction.</em></h3><p>A mobile-first attendance concept combining selfie capture, location state, and a FastAPI-ready submission flow.</p></div></div>; }
function SalesforcePreview({ view, setView, filter, setFilter }) { const cases = [['CS-001', 'Demo Customer', 'High', 'Open'], ['CS-002', 'Demo Customer', 'Medium', 'In Progress'], ['CS-003', 'Demo Customer', 'Low', 'Closed']].filter(row => filter === 'All' || row[2] === filter); return <div className="demo-app salesforce-demo"><DemoNav items={['Cases', 'Contacts', 'Reports', 'Dashboard', 'Automation']} active={view} setActive={setView} /><div className="app-main"><div className="demo-topline"><div><span className="mini-label">Learning implementation</span><h3>{view}</h3></div><div className="filter-row"><select value={filter} onChange={e => setFilter(e.target.value)}><option>All</option><option>High</option><option>Medium</option><option>Low</option></select><button className="avatar-button">ZQ</button></div></div><div className="sf-summary"><div><span>Open cases</span><strong>12</strong></div><div><span>Avg. response</span><strong>2.4h</strong></div><div><span>Escalations</span><strong>03</strong></div></div><div className="demo-table case-table"><div className="table-head"><span>Case</span><span>Customer</span><span>Priority</span><span>Status</span></div>{cases.map(row => <div className="table-row" key={row[0]} onClick={() => setView(row[0])}><span><b>{row[0]}</b></span><span>{row[1]}</span><span className={`priority ${row[2].toLowerCase()}`}>{row[2]}</span><b className={row[3] === 'Closed' ? 'closed' : 'pending'}>{row[3]}</b></div>)}</div>{view.startsWith('CS-') && <div className="case-detail"><button onClick={() => setView('Cases')}><X size={14} /></button><span className="mini-label">Case detail</span><h4>{view} · Login access issue</h4><p>Conceptual detail state for support triage, ownership, and escalation workflows.</p><div><span>Priority <b>High</b></span><span>Status <b>Open</b></span></div></div>}</div></div>; }

createRoot(document.getElementById('root')).render(<App />);
